---

- name: setup-workers | Reset kubeadm
  shell: kubeadm reset -f

- name: setup-workers | Join to Kubernetes cluster
  shell: |
    kubeadm join --skip-preflight-checks \
                 --token {{ token }} \
                 {{ groups['master'][0] }}:6443 \
                 --discovery-token-unsafe-skip-ca-verification

- name: setup-workers | Enable and restart kubelet engine
  systemd:
    name: kubelet
    daemon_reload: yes
    state: restarted
    enabled: yes